### ISSUE TITLE
Unable to create new field

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-seo#172]
<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_tphf)

**Comment by darylknight** [comment]
I can't see the conversation behind this issue, but I've got the same problem. Just installed Sprout SEO on a new website, tried to create a new meta data field, and it won't save. I'm seeing a red "Couldn’t save field" message at the top, but no validation errors.

The only line I can find in the log that might be relevant is:

`2019-09-22 04:00:27 [-][1][dava2ab8dh66d8k2uc101ors9o][info][craft\services\Fields::saveField] Field not saved due to validation error.`

**Comment by BenParizek** [comment]
@darylknight I believed we've fixed this issue in Sprout SEO v4.2.3.

Let me know if that resolves things for you.
