### ISSUE TITLE
Sprout SEO setting cann't be saved now – all switches are set to false on settings save

### ISSUE THREAD

**Issue by lexislav** [barrelstrength/craft-sprout-seo#205]
### Description (screenshots, logs, ...)

In latest Sprout SEO update, I have realized that sitemaps are not working. So I went to settings and they were disabled. As well as 404's log.

Enabling whatever switch on sitemaps and redirects tab in Sprout SEO settings is reset on save.

I am not using any config file for setting Sprout SEO, just the admin.

### Steps to reproduce

1. Open SProut SEO setting
2. Turn on Enable multi-lingual sitemaps switch (for example), save.
3. The switch goes back to off

### Additional info

- Craft edition & version | Craft Pro 3.4.18
- PHP version: 7.4.5
- Database driver & version:  MySQL 5.5.5
- Plugins & versions: Sprout SEO 4.6.0, Sprout Forms 3.11.2

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@lexislav I believe this issue was caused by the latest Sprout Forms update and it looks like you may have that installed as well. Did you recently update Sprout Forms to the latest too?

There was a bug in a migration that could reset all shared Sprout settings. The only way to fix this is to roll-back and re-run the updates or retrieve your old settings from a backup database. The latest release of Sprout Forms (v3.11.5), fixes the migration issue.

If you need to review the shared Sprout settings in the db directly, we are currently using a different method to save settings that Craft does with the Project Config. The Sprout Settings would be in the `sprout_settings` table and the below SQL statement reflects what they should roughly look like for Sprout Forms and Sprout SEO (the query is just for reference as some settings may differ in your specific install):

```
INSERT INTO `craft_sprout_settings` (`id`, `model`, `settings`, `dateCreated`, `dateUpdated`, `uid`) VALUES
('1', 'barrelstrength\\sproutbasereports\\models\\Settings', '{\"pluginNameOverride\":\"\",\"defaultPageLength\":\"50\",\"defaultExportDelimiter\":\";\"}', '2019-08-31 20:08:13', '2020-05-16 16:19:34', 'baa4d16d-32e5-43d1-8135-278e14cbc2ea'),
('3', 'barrelstrength\\sproutbasesentemail\\models\\Settings', '{\"pluginNameOverride\":\"\",\"enableSentEmails\":\"1\",\"sentEmailsLimit\":\"5000\",\"cleanupProbability\":\"1000\"}', '2020-05-16 15:29:27', '2020-05-16 16:16:42', '37ef68ad-9f77-41dd-a3ce-013bec6b1b65'),
('4', 'barrelstrength\\sproutbaseemail\\models\\Settings', '{\"pluginNameOverride\":\"\",\"enableNotificationEmails\":\"1\",\"emailTemplateId\":\"\",\"enablePerEmailEmailTemplateIdOverride\":\"\"}', '2020-05-16 15:29:27', '2020-05-16 16:06:09', 'eac7828c-c42a-4f7a-b705-10e2d3329103'),
('17', 'barrelstrength\\sproutbasesitemaps\\models\\Settings', '{\"pluginNameOverride\":\"\",\"enableCustomSections\":\"\",\"enableDynamicSitemaps\":\"1\",\"enableMultilingualSitemaps\":\"\",\"totalElementsPerSitemap\":\"501\",\"siteSettings\":{\"1\":\"1\",\"2\":\"\"},\"groupSettings\":{\"1\":\"\"}}', '2020-05-15 19:21:42', '2020-05-16 18:31:05', '87eb0db7-bf11-41fc-8aaa-850715a1420e'),
('18', 'barrelstrength\\sproutbaseredirects\\models\\Settings', '{\"pluginNameOverride\":\"\",\"structureId\":7,\"enableRedirects\":\"1\",\"enable404RedirectLog\":\"1\",\"total404Redirects\":\"250\",\"trackRemoteIp\":\"\",\"redirectMatchStrategy\":\"urlWithoutQueryStrings\",\"queryStringStrategy\":\"removeQueryStrings\",\"excludedUrlPatterns\":\"\",\"cleanupProbability\":\"1000\"}', '2020-05-16 16:41:46', '2020-05-16 18:31:00', 'ef5275b8-6054-4487-b74f-84d0d456366a');
```

_Note: For reasons I won't go into here, we currently manage some settings in this non-standard way (as the default way doesn't solve all the needs for our particular plugin use-case with some shared features between plugins). I recognize that this abstraction has caused more problems than are ideal and we're currently exploring ways to update the way settings are handled in our plugins to figure out how we can solve these issue and get things working in a more Craft-native way._

Let me know if you have any follow-up questions or if the above diagnoses doesn't seem to fit what you're seeing.

**Comment by lexislav** [comment]
I have updated all Sprout plugins (SEO, Forms), but the problem persist: I am not able to turn on sitemaps in settings and 404’s log.
The on/off switches are turned off when settings are saved.
I am also not able to access the redirects and Sitemaps tabs of SEO Plugin.
Just Globals and Settings.
Thanks

**Comment by BenParizek** [comment]
@lexislav Did you roll-back the most recent update and re-run the initial upgrade? Or just update to the latest from where you were experiencing the issue? Unfortunately, the only way to fix the issue will be to re-run the original migration and if that's not an option may have to be addressed manually.

Can you share what you have in the `sprout_settings` table? 

We'll need to get that table to reflect something like the schema I posted in the SQL statement in the previous post.

**Comment by lexislav** [comment]
I keep the plugins up-to-date (as there were other issues).
So Yes, I have just updated to the latest version from previous version.
Roll back to re-run intiial migration meens to set composer to load older plugin version (which?)
I can experiemnt withthat on local environment.

My sprout_settings table has four rows now:
1	barrelstrength\sproutbasereports\models\Settings	"{""pluginNameOverride"":"""",""defaultPageLength"":50,""defaultExportDelimiter"":"",""}"	2020-02-29 22:01:27	2020-05-15 13:51:13	a2122643-4d52-4178-8462-b09d7f4b84a1
2	barrelstrength\sproutbasereports\models\Settings	"{""pluginNameOverride"":"""",""defaultPageLength"":50,""defaultExportDelimiter"":"",""}"	2020-02-29 22:01:27	2020-05-15 13:51:13	ebc689d2-add5-45a6-aa91-e2ead48c3ae5
3	barrelstrength\sproutbasereports\models\Settings	"{""pluginNameOverride"":"""",""defaultPageLength"":50,""defaultExportDelimiter"":"",""}"	2020-04-28 09:52:26	2020-05-15 13:51:13	22ebccc7-e253-440f-8bbb-b1097b5ef3b4
4	barrelstrength\sproutbasereports\models\Settings	"{""pluginNameOverride"":"""",""defaultPageLength"":50,""defaultExportDelimiter"":"",""}"	2020-05-04 20:21:17	2020-05-15 13:51:13	69c9ac38-1e62-412e-8940-cf9dc05f8498


Thanks

**Comment by BenParizek** [comment]
@lexislav Yeah, this is what I expected. Your current tables are the ones that reflect the bug. You can see that all four settings rows are for Sprout Base Reports: `barrelstrength\sproutbasereports\models\Settings`.

If rolling back is too much trouble (I don't think just resetting the composer packages will do, because the migrations are already registered in the Craft database, so you would also have to remove the migrations from the database by upgrading from an older pre-upgrade database or removing them directly).

The main thing that needs to happen, is that each of those rows needs to get reverted to reflect all the different plugin settings. You could update the `model` row manually to these for values:

- barrelstrength\\sproutbasereports\\models\\Settings
- barrelstrength\\sproutbasesentemail\\models\\Settings
- barrelstrength\\sproutbasesitemaps\\models\\Settings
- barrelstrength\\sproutbaseredirects\\models\\Settings

And just set the `settings` column to an empty json object `{}`. That should get your settings pages loading again and you can resave them with the settings you desire from the Craft UI.

Feel free to ping me on Craft Discord (@BenParizek) if I can help you walk through anything to get this corrected.

**Comment by lexislav** [comment]
Well, I was succesfull - partialy.

I have manualy updated those 4 lines and set up settings to empty {} directly in DB



It made the Sitemaps functional (I can save the settings etc.).

I am able to save the redirects settings as well, but the Redirects tab in CP is not accesible: Server error.
Any idea?

Thanks for Your guidance, but I am not able to connect to Discord right now.

**Comment by BenParizek** [comment]
@lexislav Sorry for the tediousness here. Redirects do have a setting that probably needs to be set and may take some digging to find. 

Here are some default settings you can copy in for the Redirects settings `barrelstrength\sproutbaseredirects\models\Settings`.

```
{"pluginNameOverride":"","structureId":"X","enableRedirects":"1","enable404RedirectLog":"1","total404Redirects":"250","trackRemoteIp":"","redirectMatchStrategy":"urlWithoutQueryStrings","queryStringStrategy":"removeQueryStrings","excludedUrlPatterns":"","cleanupProbability":"1000"}
```

You will need to update the `structureId` value manually. This is created when you install Sprout SEO, as Sprout SEO stores your data like a structure (so you can reorder it).

This value can be found in your `craft_structures` table but it may not be obvious which structure ID it is if you have more than one. To figure out which ID it is you may need to:

- Search in the `craft_elements` table for an existing Redirect Element type `barrelstrength\sproutbaseredirects\elements\Redirect`
- Grab the ID of that redirect, i.e. `1234` (this is the Element ID of the Redirect)
- Look in the `craft_structureelements` table for a row with a matching `elementId` i.e. 456
- Grab the `structureId` from the row that matches Element ID
- Update the `structureId` value in your Redirect settings JSON to use that number `"structureId":"X"` => `"structureId":"456"`

**Comment by lexislav** [comment]
Thanks a lot for this: it is all working now !!!

**Comment by BenParizek** [comment]
Thanks for the help in troubleshooting. Glad we got it resolved.
